version: '3'

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - 27017:27017
  ntpapi:
    image: ntpapi
    build:
      context: .
      dockerfile: NtpApi/Dockerfile
